name: tt

on:
  schedule:
    - cron: "0 */1 * * *"  #
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Install Python and System Dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg mpv vlc unzip
          python -m pip install --upgrade pip
          pip install requests python-vlc streamlink

    - name: Unzip protected Python script
      env:
        ZIP_PASS: ${{ secrets.ZIP_FILEMR }}
      run: unzip -o -P "$ZIP_PASS" mxrtcode.zip

    - name: Run Python script
      run: python mxrtcode.py

    - name: Delete script after running
      if: always()
      run: rm -f mxrtcode.py

    - name: Clone target private repository
      run: |
        git clone https://x-access-token:${{ secrets.TARGET_TOKEN2X }}@${{ secrets.TARGET_URLX }} ${{ secrets.TARGET_NAMEX }}

    - name: Copy selected playlist files to target repository
      run: |
        cp *.txt ${{ secrets.TARGET_NAMEX }}/ || true
        cp *.json ${{ secrets.TARGET_NAMEX }}/ || true

    - name: Commit & push to target repository
      run: |
        cd ${{ secrets.TARGET_NAMEX }}
        git config user.name "${{ secrets.TARGET_REPO_USER }}"
        git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
        git add .
        git commit -m "Auto update playlist on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
