push: tt

on:
  schedule:
    - cron: "0 */1 * * *"  # Run every 1 hour
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4
    
    - name: Install Python and System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg unzip
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Unzip protected Python script
      env:
        ZIP_PASS: ${{ secrets.ZIP_FILEMR }}
      run: |
        unzip -o -P "$ZIP_PASS" pp-fp-c.zip
        echo "✓ Script Unzipped Successfully"
    
    - name: Run Python script
      run: |
        python pp-fp-c.py || echo "⚠ Script Error Ignored for Continuity"
    
    - name: Delete script after running
      if: always()
      run: rm -f pp-fp-c.py
    
    - name: Clone target private repository
      run: |
        git clone https://x-access-token:${{ secrets.TARGET_TOKEN2XMRC }}@${{ secrets.TARGET_URLXMRC }} ${{ secrets.TARGET_NAMEXMRC }}
    
    - name: Copy only playlist files to target repository
      run: |
        cp *.m3u ${{ secrets.TARGET_NAMEXMRC }}/ || echo "⚠ No playlist found"
    
    - name: Commit & push to target repository
      run: |
        cd ${{ secrets.TARGET_NAMEXMR }}
        git config user.name "${{ secrets.TARGET_REPO_USER }}"
        git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
        git add .
        git commit -m "Auto update playlist on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
