name: tt

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Install Python dependencies
      run: |
          python -m pip install --upgrade pip
          pip install requests

    - name: Unzip protected Python script
      env:
        ZIP_PASS: ${{ secrets.ZIP_FILET }}
      run: unzip -o -P "$ZIP_PASS" pxcode.zip

    - name: Run Python script
      run: python pxcode.py

    - name: Delete script after running
      if: always()
      run: rm -f pxcode.py

    - name: Ensure target directory variable exists
      run: |
        if [ -z "${{ secrets.TARGET_NAMEX }}" ]; then
          echo "TARGET_NAMEX is empty. Please set the secret correctly."
          exit 1
        fi

    - name: Remove existing folder if any
      run: |
        if [ -d "${{ secrets.TARGET_NAMEX }}" ]; then
          rm -rf "${{ secrets.TARGET_NAMEX }}"
        fi

    - name: Clone target private repository
      run: |
        git clone "https://x-access-token:${{ secrets.TARGET_TOKEN2X }}@${{ secrets.TARGET_URLX }}" "${{ secrets.TARGET_NAMEX }}"

    - name: Copy selected playlist files to target repository
      run: |
        cp -v *.m3u "${{ secrets.TARGET_NAMEX }}/" || true
        cp -v *.json "${{ secrets.TARGET_NAMEX }}/" || true

    - name: Commit & push to target repository
      run: |
        cd "${{ secrets.TARGET_NAMEX }}"
        git config user.name "${{ secrets.TARGET_REPO_USER }}"
        git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
        git add .
        git diff-index --quiet HEAD || git commit -m "Auto update playlist on $(date '+%Y-%m-%d %H:%M:%S')"
        git push
