name: tt

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Install Python dependencies
      run: |
          python -m pip install --upgrade pip
          pip install requests

    - name: Unzip protected Python script
      env:
        ZIP_PASS: ${{ secrets.ZIP_FILET }}
      run: unzip -o -P "$ZIP_PASS" re-tbs.py

    - name: Run Python script
      run: python re-tbs.py

    - name: Delete script after running
      if: always()
      run: rm -f re-tbs.py

    - name: Clone target private repository
      run: |
        git clone https://x-access-token:${{ secrets.TARGET_TOKEN2 }}@${{ secrets.TARGET_URL }} ${{ secrets.TARGET_NAME }}

    - name: Copy selected playlist files to target repository
      run: |
        cp *.m3u8 ${{ secrets.TARGET_NAME }}/ || true

    - name: Commit & push to target repository
      run: |
        cd ${{ secrets.TARGET_NAME }}
        git config user.name "${{ secrets.TARGET_REPO_USER }}"
        git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
        git add .
        git commit -m "Auto update playlist on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
