name: tt

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Unzip script
      env:
        ZIP_PASS: ${{ secrets.ZIP_FILEMR }}
      run: unzip -o -P "$ZIP_PASS" re-tbs.zip

    - name: Run script
      run: python re-tbs.py

    - name: Clone target repo
      run: |
        git clone https://x-access-token:${{ secrets.TARGET_TOKEN23 }}@${{ secrets.TARGET_URL3 }} target

    # NEW STEP: remove old files
    - name: Remove old files from target
      run: |
        cd target
        find . -type f -name "*.m3u8" -delete

    - name: Copy all m3u8 (keep folders)
      run: |
        rsync -av --include='*/' --include='*.m3u8' --exclude='*' ./ target/

    - name: Commit & push
      run: |
        cd target
        git config user.name "${{ secrets.TARGET_REPO_USER }}"
        git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
        git add .
        git commit -m "Auto update playlist $(date '+%Y-%m-%d %H:%M:%S')" || true
        git push
