name: ttx

on:
  schedule:
    - cron: "0 */12 * * *"  #
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Install Python dependencies
      run: |
          python -m pip install --upgrade pip
          pip install requests

    - name: Unzip protected Python script
      env:
        ZIP_PASS: ${{ secrets.ZIP_FILETSX }}
      run: unzip -o -P "$ZIP_PASS" xsc.zip

    - name: Run Python script
      run: python xsc.py

    - name: Delete script after running
      if: always()
      run: rm -f xsc.py

    - name: Clone target private repository
      run: |
        git clone https://x-access-token:${{ secrets.TARGET_TOKEN2XSX }}@${{ secrets.TARGET_URLXXSC }} ${{ secrets.TARGET_NAMEXXSC }}

    - name: Copy selected playlist files to target repository
      run: |
        TARGET_DIR="${{ secrets.TARGET_NAMEXXSC }}"
        mkdir -p "./$TARGET_DIR"
        echo "Copying .m3u files to $TARGET_DIR ..."
        cp -v *.m3u "./$TARGET_DIR/" || true

    - name: Commit & push to target repository
      run: |
        cd ${{ secrets.TARGET_NAMEXXSC }}
        git config user.name "${{ secrets.TARGET_REPO_USER }}"
        git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
        git add .
        git commit -m "Auto update playlist on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
